"""empty message

Revision ID: cfcb97760178
Revises: 1cdb8c8bf162
Create Date: 2016-04-28 17:09:29.501246

"""

# revision identifiers, used by Alembic.
revision = 'cfcb97760178'
down_revision = '1cdb8c8bf162'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credit', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credit')
    ### end Alembic commands ###
